### ISSUE TITLE
The todo list

### ISSUE THREAD

**Issue by Thechiefpotatopeeler** [Thechiefpotatopeeler/eldritch-mod#1]
The stuff I plan on doing:

- [x] Make itemblocks register with textures
- [x] Add references to my friends
- [x] Mushroom race
- [x] Nibbiru and Annunaki from Sitchen works

**Comment by Thechiefpotatopeeler** [comment]
This todo list is outdated

**Comment by Thechiefpotatopeeler** [comment]
Done
